package com.titan.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.titan.model.Pest;

import com.titan.data.greendao.PestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pestDaoConfig;

    private final PestDao pestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pestDaoConfig = daoConfigMap.get(PestDao.class).clone();
        pestDaoConfig.initIdentityScope(type);

        pestDao = new PestDao(pestDaoConfig, this);

        registerDao(Pest.class, pestDao);
    }
    
    public void clear() {
        pestDaoConfig.clearIdentityScope();
    }

    public PestDao getPestDao() {
        return pestDao;
    }

}
